/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scical;

import javax.swing.JOptionPane;

/**
 *
 * @author Aditya Sharma
 */
public class scicalci extends javax.swing.JFrame {
double firstnum,secondnum,result;
String operations;
private Object math;

    /**
     * Creates new form scicalci
     */
    public scicalci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jtxtDisplay = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnmul = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtndecimal = new javax.swing.JButton();
        jbtnsub = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnadd = new javax.swing.JButton();
        jbtnplusminus = new javax.swing.JButton();
        jbtneq = new javax.swing.JButton();
        jbtnbackspace = new javax.swing.JButton();
        jbtnclr = new javax.swing.JButton();
        jbtnsqrt = new javax.swing.JButton();
        jbtndiv = new javax.swing.JButton();
        jbtnlog = new javax.swing.JButton();
        jbtnx2 = new javax.swing.JButton();
        jbtnsinh = new javax.swing.JButton();
        jbtnsin = new javax.swing.JButton();
        jbtnx3 = new javax.swing.JButton();
        jbtncosh = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jbtntan = new javax.swing.JButton();
        jbtnmodulo = new javax.swing.JButton();
        jbtncbrt = new javax.swing.JButton();
        jbtncos = new javax.swing.JButton();
        jbtnxy = new javax.swing.JButton();
        jbtntanh = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jbtnfact = new javax.swing.JButton();
        jbtnround = new javax.swing.JButton();
        jbtnbin = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        jButton9.setText("jButton2");

        jButton16.setText("jButton2");

        jButton17.setText("jButton2");

        jButton19.setText("jButton2");

        jButton20.setText("jButton2");

        jButton21.setText("jButton2");

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(20, 20));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDisplay.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.setText("0");
        getContentPane().add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 424, 31));

        jbtn7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 90, 53, 32));

        jbtn8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 90, 53, 33));

        jbtn9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 90, 53, 33));

        jbtnmul.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmulActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmul, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 90, 53, 33));

        jbtn4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 129, 53, 33));

        jbtn5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 129, 53, 33));

        jbtn1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 168, 53, 33));

        jbtn2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 168, 53, 33));

        jbtn0.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 207, 53, 33));

        jbtn6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 129, 53, 33));

        jbtndecimal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtndecimal.setText(".");
        jbtndecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndecimalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 207, 53, 33));

        jbtnsub.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnsub.setText("-");
        jbtnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsubActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsub, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 129, 53, 33));

        jbtn3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 168, 53, 33));

        jbtnadd.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnadd.setText("+");
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 168, 53, 33));

        jbtnplusminus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnplusminus.setText("±");
        jbtnplusminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusminusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnplusminus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 53, 33));

        jbtneq.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtneq.setText("=");
        jbtneq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneqActionPerformed(evt);
            }
        });
        getContentPane().add(jbtneq, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 53, 33));

        jbtnbackspace.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnbackspace.setText("←");
        jbtnbackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbackspaceActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbackspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 51, 53, 32));

        jbtnclr.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnclr.setText("C");
        jbtnclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclrActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 51, 53, 33));

        jbtnsqrt.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnsqrt.setText("√");
        jbtnsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsqrtActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 51, 53, 33));

        jbtndiv.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtndiv.setText("/");
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });
        getContentPane().add(jbtndiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 51, 53, 33));

        jbtnlog.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnlog.setText("Log");
        jbtnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 33));

        jbtnx2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnx2.setText("X^2");
        jbtnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnx2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 33));

        jbtnsinh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnsinh.setText("sinh");
        jbtnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinhActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 51, 68, 33));

        jbtnsin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnsin.setText("sin");
        jbtnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsinActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnsin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 53, 33));

        jbtnx3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnx3.setText("X^3");
        jbtnx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnx3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 33));

        jbtncosh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtncosh.setText("cosh");
        jbtncosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncoshActionPerformed(evt);
            }
        });
        getContentPane().add(jbtncosh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 68, 33));

        jButton11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton11.setText("jButton2");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 53, 33));

        jButton13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton13.setText("jButton2");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 51, 33));

        jbtntan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtntan.setText("tan");
        jbtntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanActionPerformed(evt);
            }
        });
        getContentPane().add(jbtntan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 168, -1, 33));

        jbtnmodulo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnmodulo.setText("%");
        jbtnmodulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmoduloActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnmodulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 168, 55, 33));

        jbtncbrt.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jbtncbrt.setText("³√");
        jbtncbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncbrtActionPerformed(evt);
            }
        });
        getContentPane().add(jbtncbrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 168, 68, 33));

        jbtncos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtncos.setText("cos");
        jbtncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncosActionPerformed(evt);
            }
        });
        getContentPane().add(jbtncos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, 33));

        jbtnxy.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnxy.setText("X^Y");
        jbtnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnxyActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnxy, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 129, -1, 33));

        jbtntanh.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtntanh.setText("tanh");
        jbtntanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtntanhActionPerformed(evt);
            }
        });
        getContentPane().add(jbtntanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 129, 68, 33));

        jButton25.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton25.setText("jButton2");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 53, 33));

        jButton26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton26.setText("jButton2");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 129, 55, 33));

        jButton27.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton27.setText("jButton2");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 129, 51, 33));

        jbtnfact.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnfact.setText("X!");
        getContentPane().add(jbtnfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, 53, 33));

        jbtnround.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnround.setText("round");
        jbtnround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnroundActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnround, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 60, 33));

        jbtnbin.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jbtnbin.setText("bin");
        jbtnbin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbinActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnbin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 207, 68, 33));

        jButton31.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton31.setText("jButton2");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, 53, 33));

        jButton33.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton33.setText("jButton2");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 207, 51, 33));

        jButton2.setText("Chech for Prime Number");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, 60));

        jButton3.setText("Unit Conversion");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, 50));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem1.setText("Normal/Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setText("Scientific/advanced");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Special features");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(true);
        this.setSize(245, 420);       
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(true);
        this.setSize(245, 420);      
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(true);
        this.setSize(440, 420);
        jtxtDisplay.setSize(440,39);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    private void jbtnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsubActionPerformed
firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("-");        
    }//GEN-LAST:event_jbtnsubActionPerformed

    private void jbtneqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneqActionPerformed
    String answer;
    secondnum=Double.parseDouble(jtxtDisplay.getText());
    if(operations =="+")
    {
        result=firstnum + secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);
    }
    else if(operations =="-")
    {
     result=firstnum - secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);   
    }
    else if(operations =="*")
    {
     result=firstnum * secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);   
    }
    else if(operations =="/")
    {
     result=firstnum / secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);   
    }
    else if(operations =="%")
    {
     result=firstnum % secondnum;
        answer = String.format("%.2f",result);
        jtxtDisplay.setText(answer);   
    }
    }//GEN-LAST:event_jbtneqActionPerformed

    private void jbtnsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsqrtActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sqrt(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnsqrtActionPerformed

    private void jbtnclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclrActionPerformed

        jtxtDisplay.setText("");
    }//GEN-LAST:event_jbtnclrActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn7.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn8.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
      String inum = jtxtDisplay.getText()+jbtn9.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn4.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
       String inum = jtxtDisplay.getText()+jbtn5.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn6.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn1.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn2.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String inum = jtxtDisplay.getText()+jbtn3.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
       String inum = jtxtDisplay.getText()+jbtn0.getText();
        jtxtDisplay.setText(inum);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnbackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbackspaceActionPerformed
        String bsp = null;
        if(jtxtDisplay.getText().length() > 0)
        {
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length()-1);
            bsp = strB.toString();
            jtxtDisplay.setText(bsp);
        }
    }//GEN-LAST:event_jbtnbackspaceActionPerformed

    private void jbtndecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndecimalActionPerformed
        if(!jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText()+ jbtndecimal.getText());
        }
    }//GEN-LAST:event_jbtndecimalActionPerformed

    private void jbtnplusminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusminusActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops*-1;
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnplusminusActionPerformed

    private void jbtnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnx2ActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops =( ops*ops );
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnx2ActionPerformed

    private void jbtnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnxyActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.pow(ops,ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnxyActionPerformed

    private void jbtnmoduloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmoduloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnmoduloActionPerformed

    private void jbtnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sin(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnsinActionPerformed

    private void jbtnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.log(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnlogActionPerformed

    private void jbtnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsinhActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.sinh(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnsinhActionPerformed

    private void jbtncoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncoshActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cosh(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtncoshActionPerformed

    private void jbtntanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanhActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.tanh(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtntanhActionPerformed

    private void jbtncbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncbrtActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cbrt(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtncbrtActionPerformed

    private void jbtncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncosActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.cos(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtncosActionPerformed

    private void jbtntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtntanActionPerformed
         double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.tan(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtntanActionPerformed

    private void jbtnroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnroundActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = Math.round(ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnroundActionPerformed

    private void jbtnx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnx3ActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops=(ops*ops*ops);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtnx3ActionPerformed

    private void jbtnbinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbinActionPerformed
        int a = Integer.parseInt(jtxtDisplay.getText());
        jtxtDisplay.setText(Integer.toString(a,2));        
    }//GEN-LAST:event_jbtnbinActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("+");
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("*");
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText(null);
        operations=("/");
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int num=Integer.parseInt(jtxtDisplay.getText());
int temp;
boolean isPrime;
for(int i=2;i<=num/2;i++)
{
   temp=num%i;
   if(temp==0)
   {
      isPrime=false;
      break;
      
   }
   
}
JOptionPane.showMessageDialog(this,"Number is not a prime number");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scicalci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scicalci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnbackspace;
    private javax.swing.JButton jbtnbin;
    private javax.swing.JButton jbtncbrt;
    private javax.swing.JButton jbtnclr;
    private javax.swing.JButton jbtncos;
    private javax.swing.JButton jbtncosh;
    private javax.swing.JButton jbtndecimal;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtneq;
    private javax.swing.JButton jbtnfact;
    private javax.swing.JButton jbtnlog;
    private javax.swing.JButton jbtnmodulo;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnplusminus;
    private javax.swing.JButton jbtnround;
    private javax.swing.JButton jbtnsin;
    private javax.swing.JButton jbtnsinh;
    private javax.swing.JButton jbtnsqrt;
    private javax.swing.JButton jbtnsub;
    private javax.swing.JButton jbtntan;
    private javax.swing.JButton jbtntanh;
    private javax.swing.JButton jbtnx2;
    private javax.swing.JButton jbtnx3;
    private javax.swing.JButton jbtnxy;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
